services:
  app:
    build: .
    container_name: ict_app
    ports:
      - "8284:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ict_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ict_db
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8285:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
